print("This is testData.lua from ModA")
print(GameData:TryGet("path.to.nowhere"))
print(GameData:TryGet("ModB", "bkey"))
print(GameData:TryGetFrom("ModB", "key"))
GameData:Set("path.to.nowhere", "path to nowhere")
print(GameData:TryGet("path.to.nowhere"))
GameData:SetTo("ModB", "bkey", "value set by mod A")
print(GameData:TryGetFrom("ModB", "bkey"))