print("This is scriptJ.lua from ModJ.")
-- GameData:AllPathHistoriesFor("Core")
local somePath, somePathExists = GameData:TryGetFrom("Core", "somePath")
print("Core mod, path somePath exists: ")
print(somePathExists)
print(Mods.Ids())