print("This is scriptJ.lua from ModJ.")
local somePath, somePathExists = GameData.TryGet("somePath", "Core")
print("Core mod, path somePath exists: ")
print(somePathExists)
print(Mods.Ids())
Texture.TryRegister()
Texture.TryRegister("dd","dd","ddd","ddddd")
print(Mods.CurrentId())
print(Animation)
local baseComp1, exist1 = Animation.TryGetBaseComponent("player")
print(baseComp1, exist1)
local baseComp2, exist2 = Animation.TryGetBaseComponent("player", "Core")
print(baseComp2, exist2)